description: Security Best Practices for Secrets Manager
schemaVersion: '1.0'
templateBody:
  Parameters:
    SecretsmanagerSecretPeriodicRotationParamMaxDaysSinceRotation:
      Default: 'not-a-number'  # Invalid parameter type - should be number
      Type: InvalidType  # Invalid type

  Resources:
    SecretsmanagerRotationEnabledCheck:
      Properties:
        ConfigRuleName: secretsmanager-rotation-enabled-check
        Scope:
          ComplianceResourceTypes:
          - AWS::SecretsManager::Secret
        Source:
          Owner: AWS
          SourceIdentifier: SECRETSMANAGER_ROTATION_ENABLED_CHECK
        InvalidField: "This shouldn't be here"  # Invalid field
      Type: AWS::Config::ConfigRule

    SecretsmanagerScheduledRotationSuccessCheck:
    Properties:  # Wrong indentation
    ConfigRuleName: secretsmanager-scheduled-rotation-success-check  # Wrong indentation
    Scope:  # Wrong indentation
      ComplianceResourceTypes:
      - AWS::SecretsManager::Secret
    Source:
      Owner: AWS
      SourceIdentifier: SECRETSMANAGER_SCHEDULED_ROTATION_SUCCESS_CHECK
    Type: AWS::Config::ConfigRule  # Wrong indentation

    SecretsmanagerSecretPeriodicRotation:
      Properties:
        ConfigRuleName: secretsmanager-secret-periodic-rotation
        InputParameters:
          maxDaysSinceRotation: {  # Missing closing brace
        Source:
          Owner: AWS
          SourceIdentifier: SECRETSMANAGER_SECRET_PERIODIC_ROTATION
      Type: AWS::Config::ConfigRule

    SecretsmanagerSecretUnused:
      Properties:
        ConfigRuleName: secretsmanager-secret-unused
        InputParameters:
          unusedForDays: "invalid-string"  # Invalid parameter type
        Source:
          Owner: AWS
          SourceIdentifier: SECRETSMANAGER_SECRET_UNUSED
      Type: AWS::Config::ConfigRule

    SecretsmanagerUsingCmk:
      Properties:
        ConfigRuleName: secretsmanager-using-cmk
        Scope:
          ComplianceResourceTypes:
          - AWS::SecretsManager::Secret
        Source:
          Owner: INVALID_OWNER  # Invalid owner
          SourceIdentifier: SECRETSMANAGER_USING_CMK
      Type: AWS::Config::ConfigRule